package com.model;

/**
 * TBanji generated by MyEclipse Persistence Tools
 */

public class TBanji implements java.io.Serializable {

	private Integer id;
	private String mingcheng;
	private String banzhuren;
	private String loginname;
	private String loginpw;
	private String del;

	public TBanji() {
	}

	/** full constructor */
	public TBanji(String mingcheng, String del) {
		this.mingcheng = mingcheng;
		this.del = del;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMingcheng() {
		return this.mingcheng;
	}

	public void setMingcheng(String mingcheng) {
		this.mingcheng = mingcheng;
	}

	public String getDel() {
		return this.del;
	}

	public void setDel(String del) {
		this.del = del;
	}

	public String getBanzhuren() {
		return banzhuren;
	}

	public void setBanzhuren(String banzhuren) {
		this.banzhuren = banzhuren;
	}

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginpw() {
		return loginpw;
	}

	public void setLoginpw(String loginpw) {
		this.loginpw = loginpw;
	}

}