package com.model;

import java.util.Date;
import java.util.List;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable {
	private Integer userId;
	private Integer banjiId;
	private String userName;
	private String userPw;

	private String userRealname;
	private String userSex;
	private String userAddress;
	private String userTel;

	private String userDel;

	private TBanji banji;

	private int zongfen;

	private List chengjiList;

	public String getUserAddress() {
		return userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserDel() {
		return userDel;
	}

	public void setUserDel(String userDel) {
		this.userDel = userDel;
	}

	public Integer getBanjiId() {
		return banjiId;
	}

	public void setBanjiId(Integer banjiId) {
		this.banjiId = banjiId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public TBanji getBanji() {
		return banji;
	}

	public void setBanji(TBanji banji) {
		this.banji = banji;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public String getUserRealname() {
		return userRealname;
	}

	public int getZongfen() {
		return zongfen;
	}

	public void setZongfen(int zongfen) {
		this.zongfen = zongfen;
	}

	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}

	public String getUserSex() {
		return userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public String getUserTel() {
		return userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	public List getChengjiList() {
		return chengjiList;
	}

	public void setChengjiList(List chengjiList) {
		this.chengjiList = chengjiList;
	}

}